#! /bin/sh

#  
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#                                               
#  https://github.com/baskerville/bspwm
#

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width          1
bspc config normal_border_color   \#222222
bspc config focused_border_color  \#444444
#bspc config focused_border_color  \#FFFFFF
bspc config window_gap            10
bspc config top_padding           30
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move


bspc rule -a feh state=floating
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled
bspc rule -a Zathura state=tiled
bspc rule -a Nm-connection-editor state=floating
bspc rule -a pavucontrol state=floating


killall -w sxhkd polybar picom dunst &
sleep 0.1
wmname LG3D &
dunst &
picom &
feh --bg-fill --no-fehbg  ~/Pictures/wallpaper.png &
unclutter --ignore-scrolling --timeout 10 &
sxhkd &
polybar bspwm
